name: "L!bra"
version: "0.1.0"
bundle_identifier: "com.RazorBackRoar.Libra"
author: "Antigravity"
description: "A new macOS Python application."
python_version: "3.9"
base_path: "."
src_path: "./src"
resources_path: "./resources"
tests_path: "./tests"
build_path: "./build"
dist_path: "./dist"
